auth:
  enabled: false
  token:
    expire_minutes: 360
logging:
  level:
    root: INFO
server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  application:
    name: springboot-jpa
  datasource:
    password: root1234
    url: jdbc:mysql://localhost:3306/skyprobe
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    show-sql: true
  main:
    banner-mode: 'off'
springdoc:
  swagger-ui:
    path: /swagger-ui.html
